addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

env:
  - CC=gcc-5

cache:
  directories:
    - $HOME/.cache/rebar3
    - $TRAVIS_BUILD_DIR/_build

install: true

language: erlang

otp_release:
  - 19.3
  - 19.0
  - 18.3
  - 17.5

script: "./rebar3 eunit"

sudo: false